### ISSUE TITLE
CN区好文推荐

### ISSUE THREAD

**Issue by think-in-universe** [steem-driver/condenser#11]
### Description

建一个号转发大伟和cn-curation推荐的文章，也可以转发steem-guides,team-cn,cn-activity的文章

- cn-curation的程序是软哥召唤cn-curation，然后回复点赞，再加上比如@cn-curators 转发就好了
- 大伟的就看他转发就自动跟着转发
- team-cn,cn-activity,steem-guides发帖就自动转发

**Comment by ericet** [comment]
把promoted改成recommended，当输入https://www.steemcn.org/recommended的时候，实际上显示的是@cn-curators这个账号下的帖子

* 需要修改前端
* 需要一个程序转发cn-curation,rivalhw推荐的帖子，转发@team-cn @steem-guides @cn-activity帖子

**Comment by ericet** [comment]
#45
